import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import "@fontsource/pretendard/400.css";
import "@fontsource/pretendard/500.css";
import "@fontsource/pretendard/600.css";
import "@fontsource/pretendard/700.css";
import StoreProvider from "./StoreProvider";
import { isLocale } from "@/lib/i18n";
import { ReactNode } from "react";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import AppLayoutRouter from '@/components/layout/AppLayoutRouter';
import ExtensionAttrSuppressor from '@/components/ExtensionAttrSuppressor';
import FontProvider from '@/components/layout/FontProvider';
import ContactSalesModal from '@/components/contact/ContactSalesModal';
import WebsiteAnalytics from '@/components/analytics/WebsiteAnalytics';
import { notFound } from "next/navigation";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-noto-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "아이피힌트",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
    shortcut: "/favicon.ico",
  },
};

type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({
  children,
  params,
}: Props) {
  const { locale } = await params;

  if (!isLocale(locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning className={notoSans.variable}>
      <body className="antialiased bg-white" suppressHydrationWarning>
        <ExtensionAttrSuppressor />
        <NextIntlClientProvider locale={locale} messages={messages}>
          <StoreProvider>
            <FontProvider />
            <WebsiteAnalytics />
            <AppLayoutRouter>{children}</AppLayoutRouter>
            <ContactSalesModal />
          </StoreProvider>
        </NextIntlClientProvider>
        
      </body>
    </html>
  );
}